export default {
  POSTS_SET_DATA: 'POSTS_SET_DATA',
  DELETE_POST: 'DELETE_POST',
  POSTS_GET_DATA: 'POSTS_GET_DATA',
  ADD_POST: 'ADD_POST',
  CLEAR_STATE: 'CLEAR_STATE',
  ACTIVE_POST: 'ACTIVE_POST',
};
